### ISSUE TITLE
Add Windows Container Support

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#166]
The readme makes reference to the docker features being only applicable to Linux builds.  We're now about to start using Windows containers.  I don't know if the current code makes any limitations against containers + Windows, but this is a placeholder to investigate and potentially generalize that code if needed.

**Comment by uilianries** [comment]
This is a great feature!

For now package tools uses CONAN_DOCKER_IMAGE based on clang and gcc, maybe we need to provide some support visual studio, such as lasote/conanvisual15

**Comment by lasote** [comment]
So, the windows containers run only in a windows (10) host, right? 
How are they licensed? Only matters the host license? Images with visual studio sounds good, of course. ;) It is amazing the tons of things that can be done to improve all the flows and it's a pitty to have only 24h a day ;) LoL. Dockerize all the thiiiiiings!!! :)

**Comment by uilianries** [comment]
![Dockerize all the things](https://i.imgflip.com/26v8um.jpg)

**Comment by solvingj** [comment]
They run on Windows server, which means soon Appveyor will support if they don't already.  This will hopefully free us from the random breakages we experience when they decide to change their image, just like the situation with Travis. 

I imagine there are some licensing terms and they would be the responsibility of the user to comply, but Microsoft's made all these official images available on docker so I can't imagine there's an issue for use with OSS CI services: https://hub.docker.com/u/microsoft/

**Comment by solvingj** [comment]
Very close to having this working, but there seems to be some python dependency issue relating to "extras", likely only on windows :(

Got this when running `python build.py`

It seems to happen inside the docker container. 
```
 >>  docker run  --rm -v d:\sources\git-new\CMN\vs_base:C:\Users\ContainerAdministrator/project -v C:\Users\ci\.conan:C:\Users\ContainerAdministrator/.conan -e CONAN_RUNNER_ENCODED="{\"args\": \"\", \"username\": \"ci\", \"channel\": \"testing\", \"profile\": \"\ninclude(default)\n\n[settings]\narch=x86\nbuild_type=Release\ncompiler=Visual Studio\ncompiler.runtime=MT\ncompiler.version=15\nos=Windows\n[options]\n\n[env]\nCONAN_USER_HOME=C:/jenkins_conan_tmp/build_msvc_15\n[build_requires]\n\n\", \"conan_pip_package\": \"conan==1.2.3\", \"reference\": \"vs_base/0.1.0@ci/testing\"}" -e CONAN_USERNAME=ci -e CONAN_CHANNEL=testing -e CONAN_DOCKER_HOME="C:\users\ci" -e CONAN_DOCKER_IMAGE="our-artifactory/docker/win107639-vsbt2017-vctools-py3-conan:10.0.17133.1" -e CONAN_LOGIN_USERNAME="ci" -e CONAN_PASSWORD="removed" -e CONAN_UPLOAD="our-artifactory" -e CONAN_USE_DOCKER="1" -e CONAN_UPLOAD_ONLY_WHEN_STABLE="" our-artifactory/docker/win107639-vsbt2017-vctools-py3-conan:10.0.17133.1 cmd /C "cd project && IF EXIST C:\Users\ContainerAdministrator\.conan\profiles\default del /f C:\Users\ContainerAdministrator\.conan\profiles\default && (conan profile new default --detect || true) && run_create_in_docker"
Found Visual Studio 15
Profile created with detected settings: C:\Users\ContainerAdministrator\.conan\profiles\default
Traceback (most recent call last):
  File "C:\tools\python3\Scripts\run_create_in_docker-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4; extra == "security"' distribution was not found and is required by requests
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    builder.run()
  File "d:\sources\git-python\conan-package-tools\conan\packager.py", line 444, in run
    self.run_builds(profile_name=profile_name)
  File "d:\sources\git-python\conan-package-tools\conan\packager.py", line 496, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "d:\sources\git-python\conan-package-tools\conan\create_runner.py", line 268, in run
    raise Exception("Error building: %s" % command)
Exception: Error building:  docker run  --rm -v d:\sources\git-new\CMN\vs_base:C:\Users\ContainerAdministrator/project -v C:\Users\ci\.conan:C:\Users\ContainerAdministrator/.conan -e CONAN_RUNNER_ENCODED="{\"args\": \"\", \"username\": \"ci\", \"channel\": \"testing\", \"profile\": \"\ninclude(default)\n\n[settings]\narch=x86\nbuild_type=Release\ncompiler=Visual Studio\ncompiler.runtime=MT\ncompiler.version=15\nos=Windows\n[options]\n\n[env]\nCONAN_USER_HOME=C:/jenkins_conan_tmp/build_msvc_15\n[build_requires]\n\n\", \"conan_pip_package\": \"conan==1.2.3\", \"reference\": \"vs_base/0.1.0@ci/testing\"}" -e CONAN_USERNAME=ci -e CONAN_CHANNEL=testing -e CONAN_DOCKER_HOME="C:\users\ci" -e CONAN_DOCKER_IMAGE="our-artifactory/docker/win107639-vsbt2017-vctools-py3-conan:10.0.17133.1" -e CONAN_LOGIN_USERNAME="ci" -e CONAN_PASSWORD="removed" -e CONAN_UPLOAD="our-artifactory" -e CONAN_USE_DOCKER="1" -e CONAN_UPLOAD_ONLY_WHEN_STABLE="" our-artifactory/docker/win107639-vsbt2017-vctools-py3-conan:10.0.17133.1 cmd /C "cd project && IF EXIST C:\Users\ContainerAdministrator\.conan\profiles\default del /f C:\Users\ContainerAdministrator\.conan\profiles\default && (conan profile new default --detect || true) && run_create_in_docker"

```

**Comment by lasote** [comment]
Did you find any information about what is it missing? In "regular" windows it is working, right?

**Comment by lasote** [comment]
Which python 3 version is?

**Comment by solvingj** [comment]
No i'm doing clean env, fresh install. Did both python 2 and 3.  The logs show everything getting installed.  I will provide the consolidated dockerfile for review

**Comment by lasote** [comment]
I don't think so. Anyway, I'm about to release the 0.16.5 with that change in 5 min

**Comment by leugenea** [comment]
Hello everyone!
I'm trying to get VS 2017 to work with CMake inside docker container, but looks like I'm missing something.
I've took @solvingj's Dockerfile from here: https://github.com/solvingj/conan-docker-win-testing/blob/master/win17134.1-vctools/Dockerfile and latest CMake from chocolatey (3.11.4).
When I start container, I run `VsDevCmd.bat` and `vcvars64.bat`, after that `cl.exe` could be found and seems to work just fine, but command
`conan install -r conan-center "zlib/1.2.11@conan/stable" -s compiler="Visual Studio" -s compiler.version=15 --build "zlib*"`
fails with error:
```
zlib/1.2.11@conan/stable: Calling build()
CMake Error at CMakeLists.txt:1 (PROJECT):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Users/ContainerAdministrator/.conan/data/zlib/1.2.11/conan/stable/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/zlib-1.2.11/_build/CMakeFiles/CMakeOutput.log".
```

**Comment by solvingj** [comment]
I will try to add some documentation around the windows feature to the readme today, and see if I can reproduce your issue.

**Comment by leugenea** [comment]
Thanks!

**Comment by solvingj** [comment]
Right, ultimately, I did not have success with this Dockerfile.  After some prodding, microsoft released some updated docs based on the latest images and build tools.  Here are some refs:

https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container
https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container

Try this one instead.  Of note, it took 40 minutes to build on my very fast machine, and is 21.4 GB :(

https://github.com/bincrafters/docker-vs2017bt/blob/master/Dockerfile

**Comment by leugenea** [comment]
@solvingj , yeah, I've seen this links (at least, first). So tried this Dockerfile (almost identical to one from first link):
```
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.7.1.
FROM microsoft/dotnet-framework:4.7.1

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --add Microsoft.VisualStudio.Workload.NativeDesktop `
    --add Microsoft.VisualStudio.Workload.MSBuildTools `
    --add Microsoft.VisualStudio.Workload.VCTools `
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    --all `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0
```
For this container error is same =(

**Comment by solvingj** [comment]
Ok, once i have a sharable working repository that uses the windows containers i'll post here. Might be a few days.

**Comment by leugenea** [comment]
@solvingj , any news?)

**Comment by solvingj** [comment]
@leugenea if you are interested, try this one: 
```
# escape=`

FROM microsoft/windowsservercore:1803

ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\buildtools.exe

RUN C:\TEMP\buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended  ` 
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ` 
    --add Microsoft.VisualStudio.Component.Windows10SDK.17134 `
    --add Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop `
    --add Microsoft.VisualStudio.Component.VC.140 ` 
    --add Microsoft.VisualStudio.Component.VC.ATL ` 
    --add Microsoft.VisualStudio.Component.VC.ATLMFC ` 
    --add Microsoft.VisualStudio.Component.VC.CLI.Support ` 
  || IF "%ERRORLEVEL%"=="3010" EXIT 0
  
SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]

ENV chocolateyUseWindowsCompression=false

RUN iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN choco install --yes python3 --params '"/InstallDir:C:\tools\python3"'

RUN pip install win-unicode-console

RUN pip install `
    conan `
    conan_package_tools `
    --upgrade --force-reinstall --no-cache
 
WORKDIR "C:\Users\ContainerAdministrator"
```
