### ISSUE TITLE
Bug with Docker Image

### ISSUE THREAD

**Issue by gagelarsen** [conan-io/conan-package-tools#168]
My travis-ci builds on linux using the conan docker images stopped working with no change to code. Seems it started looking for this image 'lasote/conangcc<v>-x86:latest' with the release of 0.14.0, even though I'm specifying lasote/conangcc<v> as the CONAN_DOCKER_IMAGE. 

Error I'm getting is here:

```
Using default tag: latest
Error response from daemon: pull access denied for lasote/conangcc5-x86, repository does not exist or may require 'docker login'
Unable to find image 'lasote/conangcc5-x86:latest' locally
docker: Error response from daemon: pull access denied for lasote/conangcc5-x86, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Error response from daemon: No such container: conan_runner
Error response from daemon: No such container: conan_runner
Unable to find image 'lasote/conangcc5-x86:latest' locally
docker: Error response from daemon: pull access denied for lasote/conangcc5-x86, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    builder.run()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 417, in run
    self.run_builds(profile_name=profile_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 468, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/create_runner.py", line 192, in run
    raise Exception("Error building: %s" % command)
Exception: Error building: sudo docker run --rm -v /home/travis/build/Aquaveo/xmscore:/home/conan/project -v /home/travis/.conan:/home/conan/.conan -e CONAN_RUNNER_ENCODED='{"args": "", "username": "[secure]", "channel": "stable", "profile": "\ninclude(default)\n\n[settings]\narch=x86\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++11\ncompiler.version=5\n[options]\n\n[env]\nXMSCORE_VERSION=1.0.7\nXMSCORE_RUN_TESTS=None\n[build_requires]\n\n", "conan_pip_package": "conan==1.2.0", "reference": "xmscore/1.0.7@[secure]/stable"}' -e CONAN_USERNAME=[secure] -e CONAN_CHANNEL=stable -e CONAN_REMOTES="https://conan.[secure].com:443" -e CONAN_GCC_VERSIONS="5" -e CONAN_PASSWORD_SECRET="[secure]" -e CONAN_REFERENCE="xmscore/1.0.7" -e CONAN_DOCKER_IMAGE="lasote/conangcc5" -e CONAN_UPLOAD="https://conan.[secure].com:443" -e CONAN_LOGIN_USERNAME="[secure]" -e CONAN_USER_SECRET="[secure]" -e CONAN_PASSWORD="[secure]" lasote/conangcc5-x86 /bin/sh -c "rm -f /home/conan/.conan/conan.conf && cd project && rm -f /home/conan/.conan/profiles/default && (conan profile new default --detect || true) && run_create_in_docker"
```

Travis file here:

```
env:
   global:
     # TRAVIS_BRANCH is tag name if tag provided else branch name
     - XMSCORE_VERSION: $TRAVIS_BRANCH
     - CONAN_REFERENCE: "xmscore/${XMSCORE_VERSION}"
     - CONAN_USERNAME: "aquaveo"
     - CONAN_CHANNEL: "stable"
     - CONAN_LOGIN_USERNAME: $CONAN_USER_SECRET
     - CONAN_PASSWORD: $CONAN_PASSWORD_SECRET
     - CONAN_REMOTES: $AQUAVEO_CONAN
     - GH_REPO_NAME: xmscore
     - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen/Doxyfile
     - GH_REPO_REF: github.com/Aquaveo/xmscore.git
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

stages:
    - name: test
      if: NOT tag IS present
    - name: deploy
      if: tag =~ ^\d+\.\d+\.\d+$

# Global Lifecycle Steps
# See: https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

# Install Step
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

# Build Step
script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

# After Success
after_success:
  - python test.py

# Jobs/Build Matrix
# Note: Lifecycle Steps specified in stages will override Global Lifecycle Steps
jobs:
   include:
      # --- TEST STAGE ------------------------------------------------------------------------------------------------
      - stage: test
        addons:
          apt:
            packages:
              - doxygen
              - doxygen-doc
              - doxygen-latex
              - doxygen-gui
              - graphviz
        <<: *linux
        env: TASK_NAME="DOXYGEN Generation"
        script: 
          - cd $TRAVIS_BUILD_DIR
          - chmod +x generateDocumentationAndDeploy.sh
          - ./generateDocumentationAndDeploy.sh

      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 XMSCORE_RUN_TESTS=1

      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 XMSCORE_RUN_TESTS=1

      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 XMSCORE_RUN_TESTS=1

      - stage: test
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 XMSCORE_RUN_TESTS=1
 
      # --- DEPLOY STAGE ----------------------------------------------------------------------------------------------
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_UPLOAD=$AQUAVEO_CONAN
        after_success: true

      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_UPLOAD=$AQUAVEO_CONAN
        after_success: true

      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_UPLOAD=$AQUAVEO_CONAN
        after_success: true

      - stage: deploy
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_UPLOAD=$AQUAVEO_CONAN
        after_success: true
```
Repo: https://github.com/Aquaveo/xmscore
Travis: https://travis-ci.org/Aquaveo/xmscore

**Comment by uilianries** [comment]
Same here: https://travis-ci.org/uilianries/conan-pugixml/jobs/359602474#L758

**Comment by lasote** [comment]
Thanks both for reporting. I will fix it asap. I think probably is better to rename the images. Will report asap.

**Comment by lasote** [comment]
I pushed a 0.14.1 fixing this, please confirm and close if it's working.

**Comment by uilianries** [comment]
All green! Good to go!  :tada: 

https://travis-ci.org/uilianries/conan-pugixml/builds/359794086

Thanks!

**Comment by lasote** [comment]
Many thanks again for your help friends.
