### ISSUE TITLE
Compressing large files fails on Appveyor before upload

### ISSUE THREAD

**Issue by bilke** [conan-io/conan-package-tools#17]
I have a large library ([VTK](http://www.vtk.org)) which I build on Appveyor but in debug it fails to compress all the files due to running out of memory. Can I do something about it? See also the [Appveyor-build](https://ci.appveyor.com/project/LarsBilke/conan-vtk/build/job/oo10x36cgfdsbn46).

```
Compressing package...                                                Traceback (most recent call last):
  File "C:\Python27\Scripts\conan-script.py", line 9, in <module>
    load_entry_point('conan==0.8.4', 'console_scripts', 'conan')()
  File "c:\python27\lib\site-packages\conans\conan.py", line 6, in run
    main(sys.argv[1:])
  File "c:\python27\lib\site-packages\conans\client\command.py", line 615, in main
    error = command.run(args)
  File "c:\python27\lib\site-packages\conans\client\command.py", line 529, in run
    method(args[0][1:])
  File "c:\python27\lib\site-packages\conans\client\command.py", line 437, in upload
    args.remote, all_packages=args.all, force=args.force)
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 292, in upload
    uploader.upload_conan(conan_reference, all_packages=all_packages, force=force)
  File "c:\python27\lib\site-packages\conans\client\uploader.py", line 26, in upload_conan
    self.upload_package(PackageReference(conan_ref, package_id), index + 1, total)
  File "c:\python27\lib\site-packages\conans\client\uploader.py", line 35, in upload_package
    self._remote_proxy.upload_package(package_ref)
  File "c:\python27\lib\site-packages\conans\client\proxy.py", line 205, in upload_package
    result = self._remote_manager.upload_package(package_reference, remote)
  File "c:\python27\lib\site-packages\conans\client\remote_manager.py", line 38, in upload_package
    the_files = compress_package_files(the_files)
  File "c:\python27\lib\site-packages\conans\client\remote_manager.py", line 122, in compress_package_files
    return compress_files(files, PACKAGE_TGZ_NAME, excluded=(CONANINFO, CONAN_MANIFEST))
  File "c:\python27\lib\site-packages\conans\client\remote_manager.py", line 144, in compress_files
    addfile(the_file, content, tgz)
  File "c:\python27\lib\site-packages\conans\client\remote_manager.py", line 140, in addfile
    tar.addfile(tarinfo=info, fileobj=string)
  File "c:\python27\lib\tarfile.py", line 2051, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size)
  File "c:\python27\lib\tarfile.py", line 275, in copyfileobj
    dst.write(buf)
  File "c:\python27\lib\gzip.py", line 241, in write
    self.fileobj.write(self.compress.compress(data))
MemoryError: out of memory
Traceback (most recent call last):
  File "build.py", line 8, in <module>
    builder.run()
  File "C:\Python27\lib\site-packages\conan\packager.py", line 244, in run
    self._upload_packages()
  File "C:\Python27\lib\site-packages\conan\packager.py", line 347, in _upload_packages
    raise Exception("Error uploading")
Exception: Error uploading

```

**Comment by lasote** [comment]
Hard to be solved...sorry

**Comment by bilke** [comment]
A short follow-up: I also experienced this on my local development machine. Switching to 64-bit Python fixed it for me locally and it also seems to work on Appveyor (build is still running), see bilke/conan-vtk@607f535.

**Comment by lasote** [comment]
Great, you can make a PR for the 64bits python
