### ISSUE TITLE
Gitlab CE build fails then number of pages is greater than number of jobs

### ISSUE THREAD

**Issue by yowidin** [conan-io/conan-package-tools#182]
Trying to build a package with 2 jobs while allocating 4 pages produces the following error:
```
Page: 3/4
There are no jobs!


 >> RUNNING UPLOAD COMMAND
   >> $ conan upload None --retry 3 --all --force --confirm -r=upload_repo
Traceback (most recent call last):
  File ".conan_build.py", line 31, in <module>
    builder.run()
  File "/home/user/.local/lib/python3.5/site-packages/conan/packager.py", line 445, in run
    self.upload_packages()
  File "/home/user/.local/lib/python3.5/site-packages/conan/packager.py", line 553, in upload_packages
    raise Exception("Error uploading")
Exception: Error uploading
ERROR: Job failed: exit code 1
```

Contents of the .gitlab-ci.yml:
```
variables: { CONAN_TOTAL_PAGES: '4' }
cache: { untracked: false }

stages:
    - build

.job_template: &job
    image: docker.pb.omp.de/conan-client:latest
    stage: build
    tags: [docker]
    only: [master]
    script:
        - CONAN_CURRENT_PAGE=${PAGE} python3 .conan_build.py

page1: { <<: *job, variables: { PAGE: '1' } }
page2: { <<: *job, variables: { PAGE: '2' } }
page3: { <<: *job, variables: { PAGE: '3' } }
page4: { <<: *job, variables: { PAGE: '4' } }

```

Full build log for page 3:
```
$ CONAN_CURRENT_PAGE=${PAGE} python3 .conan_build.py
upload_repo: http://our.bintray.name.com:9300 [Verify SSL: True]

 >> CI DETECTED: GITLAB

 >> BRANCH DETECTED
   >> master

 >> INFO
   >> Redefined channel by CI branch matching with 'master', setting CONAN_CHANNEL to 'stable'
bintray: http://our.bintray.name.com:9300 [Verify SSL: False]

[local_vars]
+---------------------------+--------------------------------------+
| Configuration             | value                                |
|---------------------------+--------------------------------------|
| use_docker                | False                                |
| clang_versions            | ['3.8', '3.9', '4.0']                |
| gcc_versions              | ['4.9', '5', '6', '7']               |
| docker_image_skip_update  | False                                |
| data_home                 | /home/user/.conan/data               |
| sudo_command              | sudo                                 |
| docker_32_images          | False                                |
| visual_runtimes           | ['MT', 'MD', 'MTd', 'MDd']           |
| build_types               | ['Release', 'Debug']                 |
| visual_versions           | ['10', '12', '14']                   |
| archs                     | ['x86', 'x86_64']                    |
| stable_channel            | stable                               |
| builds_in_current_page    | []                                   |
| total_pages               | 4                                    |
| specified_channel         | testing                              |
| username                  | user                                 |
| channel                   | stable                               |
| mingw_configurations      | []                                   |
| apple_clang_versions      | ['7.3', '8.0', '8.1']                |
| upload_only_when_stable   | False                                |
| upload                    | http://our.bintray.name.com:9300     |
| args                      |                                      |
| remotes                   | ['http://our.bintray.name.com:9300'] |
| exclude_vcvars_precommand | False                                |
| skip_check_credentials    | False                                |
| allow_gcc_minors          | False                                |
| curpage                   | 3                                    |
| conan_pip_package         | conan==1.2.1                         |
| login_username            | gitlabci                             |
| vs10_x86_64_enabled       | False                                |
+---------------------------+--------------------------------------+
sh: 1: sudo: not found

 >> RUNNING BUILDS...

[pip_update]
Change 'upload_repo' user from None (anonymous) to gitlabci
ERROR: No packages found matching pattern 'None'

 >> VERIFYING YOUR CREDENTIALS...

 >> OK! 'GITLABCI' USER LOGGED IN 'UPLOAD_REPO' 
Page: 3/4
There are no jobs!


 >> RUNNING UPLOAD COMMAND
   >> $ conan upload None --retry 3 --all --force --confirm -r=upload_repo
Traceback (most recent call last):
  File ".conan_build.py", line 31, in <module>
    builder.run()
  File "/home/user/.local/lib/python3.5/site-packages/conan/packager.py", line 445, in run
    self.upload_packages()
  File "/home/user/.local/lib/python3.5/site-packages/conan/packager.py", line 553, in upload_packages
    raise Exception("Error uploading")
Exception: Error uploading
ERROR: Job failed: exit code 1
```

**Comment by uilianries** [comment]
Do you have some project to reproduce the same environment?

I use gitlab + conan too, but I create multiple jobs instead to use pages. Anyway, I should investigate this issue.

**Comment by yowidin** [comment]
Sorry, but I don't have any public-facing projects to test it with. I can try and throw something together in case if description isn't enough
