### ISSUE TITLE
Remote 'upload_repo' already exists in remotes

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#187]
I've been getting this for a long time when running `python build.py` locally.  I haven't looked to see exactly what is happening, but it's super annoying.  Seems it's still happening in `0.17.0b1`, but now i think it might be fatal? Before it was a warning:

`conans.errors.ConanException: Remote 'upload_repo' already exists in remotes (use update to modify)`

```

Traceback (most recent call last):
  File "build.py", line 10, in <module>
    builder.run()
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/cpt/packager.py", line 304, in run
    self.run_builds(profile_name=profile_name)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/cpt/packager.py", line 399, in run_builds
    printer=self.printer)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/cpt/runner.py", line 51, in __init__
    self._uploader.remote_manager.add_remotes_to_conan()
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/cpt/remotes.py", line 79, in add_remotes_to_conan
    self._upload.name, insert=-1)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/cpt/remotes.py", line 123, in _add_remote
    self._conan_api.remote_add(name, url, verify_ssl=verify_ssl, insert=insert)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/conans/client/conan_api.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/conans/client/conan_api.py", line 660, in remote_add
    return registry.add(remote, url, verify_ssl, insert)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/conans/client/remote_registry.py", line 157, in add
    self._add_update(remote_name, remote, verify_ssl, exists_function, insert)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/conans/client/remote_registry.py", line 187, in _add_update
    exists_function(remotes)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/conans/client/remote_registry.py", line 156, in exists_function
    % remote_name)
conans.errors.ConanException: Remote 'upload_repo' already exists in remotes (use update to modify)
```

**Comment by lasote** [comment]
I see why it happens. Thanks. Will be solved in beta2
