### ISSUE TITLE
passing escape_env a list (args) fails

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#195]
https://github.com/conan-io/conan-package-tools/blob/develop/cpt/runner.py#L172

```
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    builder.run()
  File "d:\sources\git-python\conan-package-tools\cpt\packager.py", line 362, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "d:\sources\git-python\conan-package-tools\cpt\packager.py", line 458, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "d:\sources\git-python\conan-package-tools\cpt\runner.py", line 147, in run
    envs = self.get_env_vars()
  File "d:\sources\git-python\conan-package-tools\cpt\runner.py", line 191, in get_env_vars
    ret["CPT_ARGS"] = escape_env(self._args)
  File "d:\sources\git-python\conan-package-tools\cpt\runner.py", line 215, in escape_env
    return text.replace("\n", "@@").replace('"', '||')
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by lasote** [comment]
conan_package_tools==0.17.0b4
Released
