### ISSUE TITLE
conan-package-tools 0.17.1 abort with an error

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan-package-tools#216]
Hey,

I have a problem with conan-package-tools 0.17.1. With 0.16.5 this does not happen. The error seems only happen only on windows. I'm using conan 1.3.3 (but it also happens with 1.2.3). Below is the stack trace
```
Profile created with detected settings: C:\g\d2fbdcb6\0\tonka\conan-myproject\_ch\.conan\profiles\default
Traceback (most recent call last):
  File "build.py", line 12, in <module>
    builder.run()
  File "C:\g\d2fbdcb6\0\tonka\conan-myproject\env\lib\site-packages\cpt\packager.py", line 328, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\g\d2fbdcb6\0\tonka\conan-myproject\env\lib\site-packages\cpt\packager.py", line 404, in run_builds
    r.run()
  File "C:\g\d2fbdcb6\0\tonka\conan-myproject\env\lib\site-packages\cpt\runner.py", line 48, in run
    with context:
  File "C:\Python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\g\d2fbdcb6\0\tonka\conan-myproject\env\lib\site-packages\conans\client\tools\win.py", line 326, in vcvars
    new_env = vcvars_dict(*args, **kwargs)
  File "C:\g\d2fbdcb6\0\tonka\conan-myproject\env\lib\site-packages\conans\client\tools\win.py", line 307, in vcvars_dict
    name_var, value = line.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)
Running after script...
```

Greetings  
Tonka

**Comment by tonka3000** [comment]
Does nobody has this error, it happens now on all my CI servers

**Comment by danimtb** [comment]
Hi @tonka3000,

yes, that seems a Conan bug detected when using gitlab runner: https://github.com/conan-io/conan/issues/2904

It has been fixed and will be in Conan 1.4 release

**Comment by tonka3000** [comment]
@danimtb thanks for the info. Do you know when 1.4 will be approximately released?

**Comment by danimtb** [comment]
You are welcome!
Should be released at the end of this month.

Closing this then! Thanks for reporting 😄
