### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by ph03** [conan-io/conan-package-tools#22]
The zlib example fails for python3 with

```
CONAN_USERNAME=ph03 python3 build.py                                                                                                      Mi 05/18/16 21:14
zlib/1.2.8@ph03/testing export: Copied 1 '.cmake' files: FindZLIB.cmake
zlib/1.2.8@ph03/testing export: Copied 1 '.txt' files: CMakeLists.txt
zlib/1.2.8@ph03/testing: The stored package has not changed
zlib/1.2.8@PROJECT
    URL: http://github.com/lasote/conan-zlib
    License: http://www.zlib.net/zlib_license.html
Traceback (most recent call last):
  File "build.py", line 7, in <module>
    builder.run()
  File "/home/janickm/.local/lib/python3.4/site-packages/conan/packager.py", line 244, in run
    self._pack()
  File "/home/janickm/.local/lib/python3.4/site-packages/conan/packager.py", line 267, in _pack
    self._execute_build(build)
  File "/home/janickm/.local/lib/python3.4/site-packages/conan/packager.py", line 376, in _execute_build
    self._execute_test(None, settings, options)
  File "/home/janickm/.local/lib/python3.4/site-packages/conan/packager.py", line 81, in _execute_test
    conan_compiler, conan_compiler_version = self.conan_compiler_info()
  File "/home/janickm/.local/lib/python3.4/site-packages/conan/packager.py", line 388, in conan_compiler_info
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'
```

whereas with python2 it works great

```
env CONAN_USERNAME=ph03 python build.py                                                                                                   Mi 05/18/16 21:14
zlib/1.2.8@ph03/testing export: Copied 1 '.cmake' files: FindZLIB.cmake
zlib/1.2.8@ph03/testing export: Copied 1 '.txt' files: CMakeLists.txt
zlib/1.2.8@ph03/testing: The stored package has not changed
zlib/1.2.8@PROJECT
    URL: http://github.com/lasote/conan-zlib
    License: http://www.zlib.net/zlib_license.html

############## CONAN PACKAGE TOOLS ######################

DEBUG: - Skipped build, compiler mismatch: {'compiler.version': '4.6', 'arch': 'x86', 'build_type': 'Debug', 'compiler': 'gcc'}

#########################################################


############## CONAN PACKAGE TOOLS ######################

DEBUG: - Skipped build, compiler mismatch: {'compiler.version': '4.6', 'arch': 'x86', 'build_type': 'Release', 'compiler': 'gcc'}

#########################################################
```

Is it a problem on my side, or should I be able to run the tool with `python3` as well?

**Comment by lasote** [comment]
I've uploaded 0.2.16 version, Could you update and try? Thanks!

**Comment by ph03** [comment]
Yes, it works great with 0.2.16 now with `python3`, thanks a lot for fixing this so quickly!
