### ISSUE TITLE
 "Package binary not found" exception

### ISSUE THREAD

**Issue by db4** [conan-io/conan-package-tools#242]
One of my recipes fails with a strange exception:
https://travis-ci.org/db4/conan-SimpleAmqpClient/jobs/407033672
```
boost/1.66.0@conan/stable: Retrieving package ccfc1cf59508ec29a9b2acfa4d8f3288ac7aaec8 from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
Traceback (most recent call last):
  File "/usr/local/bin/run_create_in_docker", line 11, in <module>
    load_entry_point('conan-package-tools==0.18.2', 'console_scripts', 'run_create_in_docker')()
  File "/usr/local/lib/python2.7/dist-packages/cpt/run_in_docker.py", line 44, in run
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/cpt/runner.py", line 74, in run
    test_folder=self._test_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 327, in create
    test_build_folder, test_folder, conanfile_path)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/create.py", line 40, in create
    test_build_folder=test_build_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/test.py", line 39, in install_build_and_test
    keep_build=keep_build)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 280, in install
    installer.install(deps_graph, keep_build)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 259, in install
    self._build(nodes_by_level, deps_graph, keep_build, root_node)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 281, in _build
    self._handle_node_cache(node, package_id, keep_build, processed_package_references)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 300, in _handle_node_cache
    self._download_package(conan_file, package_ref, output, package_folder, node.binary_remote)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/installer.py", line 343, in _download_package
    remote, output, self._recorder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/remote_manager.py", line 252, in get_package
    raise NotFoundException("Package binary '%s' not found in '%s'" % (package_reference, remote.name))
```

Why I'm getting this? Some bintray/conan-center inconsistency?

**Comment by danimtb** [comment]
Could be a networking issue with a failed attempt to download. Tried from my end and worked fine:

*boost_profile*
```
[settings]
os=Linux
arch=x86
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6
```

Command:
```
$ conan install boost/1.67.0@conan/stable -r conan-center -pr boost
```

Output:
```
boost/1.67.0@conan/stable: Not found, retrieving from server 'conan-center'
boost/1.67.0@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 58B/58B
Downloading conanfile.py
[==================================================] 20.1KB/20.1KB
bzip2/1.0.6@conan/stable: Not found, retrieving from server 'conan-center'
bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 107B/107B
Downloading conanfile.py
[==================================================] 2.7KB/2.7KB
Downloading conan_export.tgz
[==================================================] 451B/451B
zlib/1.2.11@conan/stable: Not found, retrieving from server 'conan-center'
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 121B/121B
Downloading conanfile.py
[==================================================] 7.7KB/7.7KB
boost/1.67.0@conan/stable: Installing package
Requirements
    boost/1.67.0@conan/stable from 'conan-center' - Downloaded
    bzip2/1.0.6@conan/stable from 'conan-center' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    boost/1.67.0@conan/stable:ccfc1cf59508ec29a9b2acfa4d8f3288ac7aaec8 - Download
    bzip2/1.0.6@conan/stable:a82bcd7f1f2b5a3686c7d28a57bc68ed901f3493 - Download
    zlib/1.2.11@conan/stable:c20b77ef9e60968439b37c5054593c79c8cc8320 - Download

Cross-build from 'Windows:x86_64' to 'Linux:x86'
bzip2/1.0.6@conan/stable: Retrieving package a82bcd7f1f2b5a3686c7d28a57bc68ed901f3493 from remote 'conan-center'
Downloading conanmanifest.txt
[==================================================] 258B/258B
Downloading conaninfo.txt
[==================================================] 382B/382B
Downloading conan_package.tgz
[==================================================] 126.1KB/126.1KB
bzip2/1.0.6@conan/stable: Package installed a82bcd7f1f2b5a3686c7d28a57bc68ed901f3493
zlib/1.2.11@conan/stable: Retrieving package c20b77ef9e60968439b37c5054593c79c8cc8320 from remote 'conan-center'
Downloading conanmanifest.txt
[==================================================] 800B/800B
Downloading conaninfo.txt
[==================================================] 354B/354B
Downloading conan_package.tgz
[==================================================] 151.7KB/151.7KB
zlib/1.2.11@conan/stable: Package installed c20b77ef9e60968439b37c5054593c79c8cc8320
boost/1.67.0@conan/stable: Retrieving package ccfc1cf59508ec29a9b2acfa4d8f3288ac7aaec8 from remote 'conan-center'
Downloading conanmanifest.txt
[==================================================] 1.1MB/1.1MB
Downloading conaninfo.txt
[==================================================] 2.4KB/2.4KB
Downloading conan_package.tgz
[==================================================] 63.1MB/63.1MB
boost/1.67.0@conan/stable: Package installed ccfc1cf59508ec29a9b2acfa4d8f3288ac7aaec8
boost/1.67.0@conan/stable: LIBRARIES: ['boost_wave', 'boost_container', 'boost_contract', 'boost_exception', 'boost_graph', 'boost_iostreams', 'boost_locale', 'boost_log', 'boost_program_options', 'boost_random', 'boost_regex', 'boost_serialization', 'boost_wserialization', 'boost_signals', 'boost_coroutine', 'boost_fiber', 'boost_context', 'boost_timer', 'boost_thread', 'boost_chrono', 'boost_date_time', 'boost_atomic', 'boost_filesystem', 'boost_system', 'boost_type_erasure', 'boost_log_setup', 'boost_math_c99', 'boost_math_c99f', 'boost_math_c99l', 'boost_math_tr1', 'boost_math_tr1f', 'boost_math_tr1l', 'boost_stacktrace_addr2line', 'boost_stacktrace_backtrace', 'boost_stacktrace_basic', 'boost_stacktrace_noop', 'boost_unit_test_framework']
boost/1.67.0@conan/stable: Package folder: C:/.conan\afgorgs2\1
```

**Comment by db4** [comment]
I tried to restart that Travis CI job several times and it failed just the same way. That's why I submitted the issue. Note that you tried to install boost/1.67.0 while I had problems with 1.66.0.

**Comment by danimtb** [comment]
Seems package is downloadable from the bintray UI but NOT from the API:

https://dl.bintray.com/conan-community/conan/conan/boost/1.66.0/stable/package/ccfc1cf59508ec29a9b2acfa4d8f3288ac7aaec8/conan_package.tgz

https://api.bintray.com/conan/conan/conan-center/v1/files/conan/boost/1.66.0/stable/package/ccfc1cf59508ec29a9b2acfa4d8f3288ac7aaec8/conan_package.tgz

**Comment by db4** [comment]
> Seems package is downloadable from the bintray UI but NOT from the API

So this is a (temporary) bintray problem?

I also noticed that your first link points to `conan-community` while the second one to `conan-center`. Is it OK?

**Comment by danimtb** [comment]
Yes, it is OK and yes this is a Bintray issue. Working on a fix

**Comment by lasote** [comment]
Please, try now, it should be fixed.

**Comment by db4** [comment]
Thanks a lot, it works now.
