### ISSUE TITLE
Conan claims there are uncommitted changes after a clean build on Travis CI

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan-package-tools#432]
Conan claims there are uncommitted changes after a clean build on Travis CI so it disallows uploading the version to Bintray.

```
mp-units/0.4.0@mpusz/testing: WARN: There are uncommitted changes, skipping the replacement of 'scm.url' and 'scm.revision' auto fields. Use --ignore-dirty to force it. The 'conan upload' command will prevent uploading recipes with 'auto' values in these fields.
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.1/bin/run_create_in_docker", line 11, in <module>
    load_entry_point('conan-package-tools==0.30.3', 'console_scripts', 'run_create_in_docker')()
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/run_in_docker.py", line 53, in run
    runner.run()
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/runner.py", line 146, in run
    self._upload, package_id)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/uploader.py", line 21, in upload_packages
    self._upload_artifacts(reference, upload, package_id)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/cpt/uploader.py", line 55, in _upload_artifacts
    retry=int(self._upload_retry))
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/conan_api.py", line 881, in upload
    retry, retry_wait, integrity_check, policy, query=query)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 89, in upload
    integrity_check, policy, remote, upload_recorder, remotes)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 190, in _upload_ref
    self._upload_recipe(ref, conanfile, retry, retry_wait, policy, recipe_remote, remotes)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/cmd/uploader.py", line 234, in _upload_recipe
    raise ConanException("The recipe has 'scm.url' or 'scm.revision' with 'auto' "
conans.errors.ConanException: The recipe has 'scm.url' or 'scm.revision' with 'auto' values. Use '--force' to ignore this error or export again the recipe ('conan export' or 'conan create') in a repository with no-uncommitted changes or by using the '--ignore-dirty' option
Traceback (most recent call last):
  File "build.py", line 25, in <module>
    builder.run()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/cpt/packager.py", line 517, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/cpt/packager.py", line 639, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/cpt/runner.py", line 299, in run
    raise Exception("Error building: %s" % command)
Exception: Error building: sudo -E docker run --rm -v "/home/travis/build/mpusz/units:/home/conan/project" -e CONAN_GCC_VERSIONS="9" -e CONAN_DOCKER_IMAGE="conanio/gcc9" -e CONAN_RUN_TESTS="1" -e CONAN_PASSWORD="[secure]" -e CONAN_DOCKER_32_IMAGES="1" -e CONAN_CHANNEL="testing" -e CONAN_LOGIN_USERNAME="mpusz" -e CONAN_UPLOAD="https://api.bintray.com/conan/mpusz/conan-mpusz@True@upload_repo" -e CONAN_REFERENCE="mp-units/0.4.0@mpusz/testing" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch=x86_64@@build_type=Release@@compiler=gcc@@compiler.cppstd=20@@compiler.libcxx=libstdc++@@compiler.version=9@@[options]@@@@[env]@@@@[build_requires]@@@@" -e CONAN_USERNAME="mpusz" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_ENABLED="True" -e CPT_UPLOAD_RETRY="3" -e CPT_BUILD_POLICY="outdated" -e CPT_UPLOAD_DEPENDENCIES="all" -e CPT_CONANFILE="conanfile.py" -e PIP_PROGRESS_BAR="off" -e PIP_DISABLE_PIP_VERSION_CHECK="1"   conanio/gcc9 /bin/sh -c " cd project &&  run_create_in_docker "
The command "./.travis/run.sh" exited with 1.
Done. Your build exited with 1.
```

More info here: <https://travis-ci.com/mpusz/units/builds/136826698>

**Comment by michaelmaguire** [comment]
We are also seeing this error with Conan 1.20.4.  We use `"auto"` but have not modified the checkout in any way.  The same workflow did not have this error with Conan 1.16.1

> [Conan_pipeline] $ cmd.exe /C "conan upload nxgroups/1575@PORT/stable --all --no-overwrite recipe -r 3556d404-d783-4e2c-80ed-55c10937402c --confirm && exit %%ERRORLEVEL%%"
> ERROR: The recipe has 'scm.url' or 'scm.revision' with 'auto' values. Use '--force' to ignore this error or export again the recipe ('conan export' or 'conan create') in a repository with no-uncommitted changes or by using the '--ignore-dirty' option
> By default, attempting to version this package from the Jenkins build number
> Uploading to remote '3556d404-d783-4e2c-80ed-55c10937402c':
> Uploading nxgroups/1575@PORT/stable to remote '3556d404-d783-4e2c-80ed-55c10937402c'

Note I tried:

> expected to call org.jfrog.hudson.pipeline.common.types.ConanClient.run but wound up catching runConanCommand; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
> [Conan_pipeline] $ cmd.exe /C "conan upload nxgroups/1598@PORT/stable --all -r 2f80249c-9a82-4e20-9071-3dea2b255b0f --no-overwrite recipe --confirm --ignore-dirty && exit %%ERRORLEVEL%%"
> usage: conan upload [-h] [-p PACKAGE] [-q QUERY] [-r REMOTE] [--all]
>                     [--skip-upload] [--force] [--check] [-c] [--retry RETRY]
>                     [--retry-wait RETRY_WAIT] [-no [{all,recipe}]] [-j JSON]
>                     pattern_or_reference
> conan upload: error: unrecognized arguments: --ignore-dirty
> ERROR: Exiting with code: 2

so I guess I misunderstood the "Use '--force' to ignore this error or export again the recipe ('conan export' or 'conan create') in a repository with no-uncommitted changes or by using the '--ignore-dirty' option" instructions.
