### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by jeremy-coulon** [conan-io/conan-package-tools#494]
### Environment Details
* Conan Package Tools Version: **0.32.4**
* Operating System: **Windows**
* Operation System Version: **Windows Server 2019**
* Compiler+version: **VS2017**
* Conan version: **conan 1.25.0**
* Python version: **python 3.8**

### Steps to reproduce (Include if Applicable)
python build.py

### Build logs (Include if Available)
[build.py.txt](https://github.com/conan-io/conan-package-tools/files/4615445/build.py.txt)

Traceback (most recent call last):
  File "build.py", line 14, in <module>
    builder.add_common_builds(reference="openjdk/8u242-b08", build_all_options_values=["openjdk:jvm"])
  File "c:\Jenkins\workspace\3rd-party_openjdk_develop\.pyenv-python\lib\site-packages\cpt\packager.py", line 511, in add_common_builds
    for key in cloned_options.keys():
RuntimeError: dictionary keys changed during iteration
script returned exit code 1

**Comment by jeremy-coulon** [comment]
It seems related to feature 'build_all_options_values'.
However I don't see this error on Linux. Maybe because I use an older python.

**Comment by jeremy-coulon** [comment]
After investigation, it seems to work with python 3.8.0 but fails with python 3.7.2.

**Comment by jeremy-coulon** [comment]
After investigation, it seems to work with python 3.7.2 but fails with python 3.8.0.

**Comment by jeremy-coulon** [comment]
https://bugs.python.org/issue36452
