### ISSUE TITLE
Appveyor integration broken since yesterday

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan-package-tools#64]
https://ci.appveyor.com/project/nunojpg/conan-botan/build/job/3ckemv2apg4if2rn

```
    Running setup.py install for conan-package-tools: finished with status 'done'
Successfully installed PyJWT-1.4.2 PyYAML-3.12 asn1crypto-0.22.0 astroid-1.4.9 backports.functools-lru-cache-1.3 bottle-0.12.13 cffi-1.10.0 colorama-0.3.9 conan-0.22.3 conan-package-tools-0.3.2 configparser-3.5.0 cryptography-1.8.1 distro-1.0.4 enum34-1.1.6 fasteners-0.14.1 future-0.16.0 idna-2.5 ipaddress-1.0.18 isort-4.2.5 lazy-object-proxy-1.3.1 mccabe-0.6.1 monotonic-1.3 node-semver-0.1.1 packaging-16.8 patch-1.16 pluginbase-0.5 pyOpenSSL-17.0.0 pycparser-2.17 pylint-1.6.5 pyparsing-2.2.0 requests-2.14.1 six-1.10.0 wrapt-1.10.10
conan user
Traceback (most recent call last):
  File "C:\Python27\Scripts\conan-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests<2.14.0,>=2.7.0' distribution was not found and is required by conan
Command exited with code 1
```

**Comment by lasote** [comment]
Thanks for reporting, confirmed, I'm analyzing what happened, we have not deployed any change so I think it could be some appveyor image change or some pypi package change. will report.

**Comment by lasote** [comment]
Fixed. Please, relaunch your build to verify that it's working again. A new version of requests caused a version mismatch between conan and conan-package-tools but it has been fixed. Thanks so much for reporting.
