### ISSUE TITLE
Builds break after the latest conan and package tools release

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan-package-tools#89]
Hi everyone, after the latest release of conan and conan package tools, my builds started to break on travis and appveyor with the message "too few arguments":

https://ci.appveyor.com/project/coding3d/glew/build/1.0.5/job/wenplkoyghkwhixt

https://travis-ci.org/dimi309/glew/jobs/256090483

Locally, while trying to test the package tools, I get this output:

```

############## CONAN PACKAGE TOOLS ######################

INFO: Not additional remotes declared...

#########################################################

('Page       : ', 1)
Builds list:
[('settings', {'compiler.version': '12', 'arch': 'x86_64', 'build_type': 'Release', 'compiler.runtime': 'MT', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '12', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler.runtime': 'MTd', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '12', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler.runtime': 'MDd', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '12', 'arch': 'x86_64', 'build_type': 'Release', 'compiler.runtime': 'MD', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '14', 'arch': 'x86_64', 'build_type': 'Release', 'compiler.runtime': 'MT', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '14', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler.runtime': 'MTd', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '14', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler.runtime': 'MDd', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '14', 'arch': 'x86_64', 'build_type': 'Release', 'compiler.runtime': 'MD', 'compiler': 'Visual Studio'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
Traceback (most recent call last):
  File "build.py", line 12, in <module>
    builder.run()
  File "C:\Users\me\Source\vconan\lib\site-packages\conan\packager.py", line 281, in run
    self.run_builds()
  File "C:\Users\me\Source\vconan\lib\site-packages\conan\packager.py", line 321, in run_builds
    build_runner.run()
  File "C:\Users\me\Source\vconan\lib\site-packages\conan\test_package_runner.py", line 47, in run
    pre_command = vcvars_command(mock_sets)
  File "C:\Users\me\Source\vconan\lib\site-packages\conans\tools.py", line 183, in vcvars_command
    % (existing_version, compiler_version))
conans.errors.ConanException: Error, Visual environment already set to 15
Current settings visual version: 12
```
Everything was working fine before, online and locally. Is there something I am doing wrong because of the latest changes, or do you think there might be bugs worth looking into?

Thanks!

Dimitri

**Comment by memsharded** [comment]
Thanks for telling. I think this PR may fix it: https://github.com/conan-io/conan-package-tools/pull/90

We'll try to release a new version asap.

**Comment by dimi309** [comment]
Many thanks for the quick response! I'll try with the new version when it gets released.

**Comment by uilianries** [comment]
Now it's working!

https://travis-ci.org/uilianries/conan-cpprestsdk/jobs/256277345

 Have a nice weekend!

**Comment by dimi309** [comment]
I also confirm that my builds are working normally once again. Thank you!
